### ISSUE TITLE
GDPR - DSGVO violation?

### ISSUE THREAD

**Issue by FlorianEisenmenger** [heimrichhannot/contao-haste_plus#17]
I find in the code prefix:"https://www.gstatic.com/charts" or {prefix}/{version}/js/jsapi_compiled_{package}_module.js or ["util/util.css","core/ tooltip.css"] - these things are loaded from gstatic servers. This is not compatible with the GDPR.
Can the content be loaded locally?

See here:
https://community.contao.org/de/showthread.php?84041-heimrichhannot-contao-haste_plus-DSGVO-Versto%C3%9F-durch-gstatic-com

**Comment by koertho** [comment]
This seems to be related to the google charts function of haste_plus. I think you can disable in in your page layout.

Why you're using haste_plus? I want to point to the readmes `This bundle is deprecated and not actively maintained anymore!`

**Comment by FlorianEisenmenger** [comment]
I am not using it activly but because it is a dependency of heimrichhannot/contao-notification_center_plus.

In the page layout there is no button / section "google charts"...

**Comment by koertho** [comment]
There is a section "components" where you can disable js components. There should be also google charts. 

Why you're using notification center plus? This is also really old stuff ;)

**Comment by FlorianEisenmenger** [comment]
I have deleted the extension - it was running for 4 years. :)
