### ISSUE TITLE
Allow haste 5

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-haste_plus#18]
Eure Erweiterung setzt zwar auch php ^8.0 vorraus aber die weitere require [codefog/contao-haste](https://packagist.org/packages/codefog/contao-haste): >=4.10,<5-dev ist nicht für PHP ^8 vorgesehen. Es gibt dort aber mit der Versio 5.0.1 auch die PHP 8.1 Kompatibilität. Könntet ihr eine Version machen die das require auf codefog/contao-haste: ^5.0 setzt?

**Comment by koertho** [comment]
Ich weiße gerne nochmal auf den obersten Hinweiß der Readme hin:

> This bundle is deprecated and not actively maintained anymore!

Bedeutet, dass wir hier keine Energie mehr reinstecken, nur noch notwendige Änderungen einbauen, wenn wir bei einem alten Projekt das noch nicht ersetzen können. Bedeutet wiederrum, dass wir dieses Modul sehr wahrscheinlich nicht für Contao 5 und Haste 5 anpassen werden. Die Änderung ist auch nicht auf eine simple Änderung in der composer.json beschränkt.

 Daher die Frage: wieso benötigst du haste_plus?

**Comment by plorenz-etes** [comment]
Ich habe das selbe Problem. haste_plus benötige ich, weil folgende Erweiterung davon abhängig ist: https://github.com/heimrichhannot/contao-tagsinput

**Comment by koertho** [comment]
Haste 4.x unterstützt doch PHP 8, ich sehe da kein Problem. Wir haben es selbst auch mit PHP 8 im Einsatz.

**Comment by plorenz-etes** [comment]
Das stimmt natürlich, allerdings verwenden andere Erweiterungen mittlerweile auch Haste 5.x, z.B. das notification_center. Dadurch entsteht dann ein Konflikt, da haste-plus explizit haste in Version 4.x required.
Grundsätzlich brauche ich haste_plus nicht in diesem Projekt, aber `heimrichhannot/contao-tagsinput` ist leider davon abhängig.

**Comment by koertho** [comment]
Perspektivisch werden wir es wohl umsetzen, aber ich kann keinen konkrekten Zeitrahmen nennen.

**Comment by koertho** [comment]
Fixed in 1.16.0
