### ISSUE TITLE
Missing Class Mysqli

### ISSUE THREAD

**Issue by Xirdion** [heimrichhannot/contao-haste_plus#4]
Since Version 1.9 there is an error when warming up the cache.
In the file QueryHelper.php on line 487 it is tried to load the class Mysqli from the namespace "Contao\Database". But this class does not exist.

I think the class should only be loaded when Contao-Version is smaller than 4.0
`if (version_compare(VERSION, '4.0', '<'))`
But I am getting this error with Contao-Version 4.4.13.
PHP-Version 7.2 (same on 7.1.6)

`Attempted to load class "Mysqli" from namespace "Contao\Database".  Did you forget a "use" statement for another namespace? `

**Comment by Defcon0** [comment]
Just tagged 1.9.1. Should work now, could you please check if it works on your system?

**Comment by Defcon0** [comment]
OK, fixed another bug in the module, 1.9.2 should work now.

**Comment by Xirdion** [comment]
Hi. Thank you very much for the fast answer. Now everything works again.
