### ISSUE TITLE
Zusätzliche Javascripte deaktivieren

### ISSUE THREAD

**Issue by akroii** [heimrichhannot/contao-haste_plus#5]
Wenn die Erweiterung `heimrichhannot/contao-upload_filename_sanitizer` installiere wird automatisch die Erweiterung `haste_plus` als Abhängigkeit geladen.
Leider wird ungefragt im Frontend verschiedene Javascripte wie geo.js, haste_plus.min.js, environment.min.js, dom.min.js usw.. geladen.
Gibt es einen Weg, dass diese Javascripte nicht automatisch ins Frontend gezogen werden?

Im Backend habe ich keine Möglichkeit die Scripte zu deaktivieren.

Ggf. kann ich das array in der localconfig überschreiben?

**Comment by fatcrobat** [comment]
Du solltest im Seitenlayout dir den Punkt „Komponenten deaktivieren“ mal ansehen, dort kannst du alle Javascript-Dateien individuell deaktivieren.

**Comment by reluem** [comment]
Leider funktioniert das Deaktivieren bei mir in 4.5.10 nicht mehr. Im FE werden weiterhin alle Skripte geladen.
<img width="750" alt="bildschirmfoto 2018-08-10 um 00 46 13" src="https://user-images.githubusercontent.com/17430489/43929817-d057fba6-9c36-11e8-841f-b0c6370acddc.png">
<img width="554" alt="bildschirmfoto 2018-08-10 um 00 46 35" src="https://user-images.githubusercontent.com/17430489/43929850-ebaabed4-9c36-11e8-90d6-9fdf7ef524d4.png">

**Comment by koertho** [comment]
@reluem Bitte ein neues Issue dafür aufmachen und bitte auch dazu schreiben, mit welchem Bundle Haste_plus mitkam. Wir entwickeln dies eigentlich nicht mehr weiter. Für viele Erweiterungen haben wir bereits Contao 4 Bundle, welche dann unter Utils-Bundle nutze.
