### ISSUE TITLE
haste_plus scripts in Konflikt mit externem Javascript

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-haste_plus#7]
haste_plus wurde bei mir als Abhängigkeit installiert, ich weiß jedoch nicht von welcher anderen Erweiterung.
Nun versuche ich ein Codesnippet zu integrieren, das ein Anmeldeformular für ein externes Newsletter-Tool beinhaltet.
Dieses Snippet enthält unter anderem auch ein ReCaptcha-Script, das extern geladen wird und mit document.write operiert.
Das Snippet macht jedoch Probleme, wenn haste_plus installiert ist. Es kommt dann zu sehr langen Wartezeiten von ca. 1 Minute, während derer der Browser komplett blockiert ist. Je nach Browser werden auch Warnungen wegen des blockierenden Scripts angezeigt.

Was kann ich tun?
Warum werden überhaupt 10 separate Javascript-Ressourcen (haste_plus.min.js, environment.min.js etc.) geladen, selbst wenn ich kein einziges JS-Template oder J-Template verwende? Kann ich das Laden der haste-Scripts im Header unterdrücken?

**Comment by fatcrobat** [comment]
Du kannst das Javascript im Seitenlayout unterr Komponenten deaktivieren, entfernen. Solltest du die Google Maps Funkion nicht verwenden, dann einfach in den systemeinstellungen die option load google maps on demand aktivieren.

**Comment by rustykowski** [comment]
Das hat mir sehr viel weiter geholfen, danke! Das JS funktioniert nun nach Deaktivierung der Komponenten einwandfrei.
Die Option "load google maps on demand" gibt es bei mir allerdings nicht in den Systemeinstellungen unter Haste Settings.
