### ISSUE TITLE
2x //maps.google.com/maps/api/js -> You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

### ISSUE THREAD

**Issue by petrad** [heimrichhannot/contao-haste_plus#9]
If haste_plus and the module "delahaye/dlh_googlemaps" are installed, the Google Maps API is included twice:
```
<script src="https://maps.googleapis.com/maps/api/js?key=...&language=de"></script>
<script src="//maps.google.com/maps/api/js?key=..."></script>
```

Is it possible to deactivate this integration in haste_plus?

Thanks in advanced,
Petra

**Comment by fatcrobat** [comment]
In system settings there is an checkbox to achieve that: loadGoogleMapsAssetsOnDemand
